/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PaymentRecord } from "./PaymentRecord";
export * as factories from "./factories";
export { PaymentRecord__factory } from "./factories/PaymentRecord__factory";
